# Project information
site_name: Gluu Scan API Documentation
site_description: Gluu Scan API Deployment and Operation References
site_author: Gluu, Inc.
site_url: https://docs.gluu.org

# Copyright
copyright: Copyright &copy; 2023, Gluu

# Repository
docs_dir: ./docs
repo_name: GitHub
repo_url: https://github.com/GluuFederation/docs-scan-api-prod
edit_uri: edit/main/docs/

# Plugins
plugins:
   - tags
   - search
   - git-revision-date-localized:
       type: timeago
       enable_creation_date: true
   - git-committers:
       repository: GluuFederation/docs-scan-api-prod
       
# Configuration
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - java
        - bash
        - python
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    language: 'en'
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          primary: green
          accent: green
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: green
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: green
          accent: green
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference
    logo: 'assets/logo/gluu.png'
    favicon: 'assets/logo/favicon.ico'
    features:
        - toc.autohide
          - search.suggest
          - search.highlight
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
extra_css:
  - css/tabs.css
  - stylesheets/mermaid-extra.css

# Extensions
markdown_extensions:
- admonition
- attr_list
- toc:
    permalink: '#'
- codehilite
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GluuFederation/docs-scan-api-prod
      name: Gluu Flex on GitHub
    - icon: fontawesome/solid/link
      link: https://gluu.org
      name: Gluu Website
  version:
    provider: mike
    default: stable
    
# Navigation
nav:
